format_version: 10                # pipeline version from gocd, based on this options would vary 
pipelines: 
  frontend:                                             # name of the pipeline job that will be showing on UI
    group: App-Deployments
    label_template: "${COUNT}"
    materials:
      mysql-code:
        git: https://github.com/DRT9999/Ansible.git
        branch: main
        auto_update: true 
        shallow_clone: true
        display_order: -1
        lock_behavior: none
    stages:                                       
      - dev:                                        # Name of the stage 
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false
          environment_variables:
            env: dev
            COMP: frontend
          secure_variables:
              ssh_pwd: "AES:dT32hCnvveJA2n0MFS/O9w==:yIrj6vXbBFzJHR7qOMNt/w=="
              pwd : "AES:KePqhoxGiGZuSNMAOE9OVg==:SYZ6XIfzC9cyGMyH4PaS9A=="             
          jobs:
            Build:
              tasks:
                - exec:
                    command: bash 
                    arguments:
                    - init.sh
                    working_directory: ALL_ENV_Ansible 

      - qa:                                        # Name of the stage 
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            Build:
              tasks:
                - exec:
                    command: ls
                    arguments:
                    - lrt